language: cpp
dist: bionic
matrix:
    include:
        - os: linux
          compiler: clang

        - os: linux
          compiler: gcc

        - os: osx
          osx_image: xcode9.3

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - make test
